config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin/dashboard' => 'admins#dashboard'
  resources 'categories'
  resources 'resources'
  root 'homepage#index'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
    
      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :category_id %><br>
  <%= f.select :category_id, options_for_select(@categories.collect{ |u| [u.category_name, u.id] },{prompt: 'Select Person'})%>
  <br>
  <br>
  <%= f.label :url_link %><br>
  <%= f.text_area :url_link %><br>
  <br>
  <%= f.label :descriptions %><br>
  <%= f.text_area :descriptions %><br>
  <br>
  <%= f.file_field :images %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_header.html.erb
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      </button>
	      <%= link_to "", root_path , {class: "navbar-brand" } %>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <% @categories.each do |category| %>
	        <li><%= link_to category.category_name , category %></li>
	        <% end %>
	      </ul>
	      <ul class="nav navbar-nav-right col-md-4">
      		<div id="custom-search-input">
          	<%= form_tag(root_path, :method => "get", id: "search-form") do %>
          	<div class="input-group">
          	<%= text_field_tag :search, params[:search], placeholder: "Search Posts" , class: "form-control input-default" %>
                  	<span class="input-group-btn">
                  	<%= button_tag(type: 'submit', class: 'btn btn-info btn-default' ) do %>
                  	<%= content_tag(:i, '', class: 'glyphicon glyphicon-search') %>
                  	<% end %>
             		</span>
          	</div>
          	<% end %>
      		</div>
      	   </ul>
	      </div><!--/.nav-collapse -->
	    </div>
	  </nav>
	  <div class="px-header">
	    <div class="container center">
	      <h3><strong>All Resources</strong> <small>: : Pixfuel is providing quality web and graphic resources. Take a look all web and graphic design resources.</small></h3>
	    </div>
	  </div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></p></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render'form' %>

app/views/resources/show.html.erb
<%= render 'header' %>
<!-- Begin page content -->
<div class="container">
	<div class="col-md-12">
		<div class="col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<%= image_tag @resource.images.url(:original) %>
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<div class="panel panel-default right-content">
				<div class="panel-body desc-content">
					<h3><strong><%= @resource.title %></strong></h3>
					<small>Submited <%= time_ago_in_words(@resource.created_at - 1) %></small>
					<div class="pull-right">
						<span class="glyphicon glyphicon-eye-open"></span> <%= "#{@resource.impressionist_count(:filter=>:session_hash)}" %>
					</div>
					<hr/>
					<p><%= @resource.descriptions %></p>
				</div>
				<div class="panel-footer">
					<%= button_to @resource.url_link, {:class => "btn btn-success",:method => :get} do %>
					Get Resource <span class="glyphicon glyphicon-download-alt"></span>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="row col-md-12">
		<div class="headrelatedResource">
			<h3>Related Resources</h3>
		</div>
		<% @relatedresource.each do |relresource| %>
		<div class="col-md-4">
			<div class="card">
				<div class="card-image">
					<%= image_tag relresource.images.url() %>
					<span class="card-title"><%= link_to relresource.title, relresource %></span>
				</div>
				<div class="card-action">
					<p>Submited <%= time_ago_in_words(relresource.created_at - 1) %> in <%= link_to relresource.category.category_name , category_path(relresource.category_id) %></p>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>
<footer class="footer">
	<div class="container">
		<p class="text-muted"> Pixfuel Copyright 2015.</p>
	</div>
</footer>