config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin/dashboard' => 'admins#dashboard'
  resources 'categories'
  resources 'resources'
  root 'homepage#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :category_name, use: :slugged
	has_many :resources

	rails_admin do

    	update do
      		field :category_name
    	end

    	list do
      		field :category_name
    	end

    	create do
      		field :category_name
    	end
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin! , except: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  		@category = Category.friendly.find(params[:id])
		@categories = Category.all.order("created_at DESC")
  		@resource = @category.resources.page params[:page]
	end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  	@category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category]
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :category_name %><br>
  <%= f.text_field :category_name %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_header.html.erb
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      </button>
	      <%= link_to "", root_path , {class: "navbar-brand" } %>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <% @categories.each do |category| %>
	        <li><%= link_to category.category_name , category %></li>
	        <% end %>
	      </ul>
	      <ul class="nav navbar-nav-right">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
      </ul>
	      </div><!--/.nav-collapse -->
	    </div>
	  </nav>
	  <div class="px-header">
	    <div class="container center">
	      <h3><strong>All Resources</strong> <small>: : Pixfuel is providing quality web and graphic resources. Take a look all web and graphic design resources.</small></h3>
	    </div>
	  </div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render 'header' %>
  <!-- Begin page content -->
  <div class="container">
    <% @resource.each_slice(3) do |resources| %>
    <div class="row content">
      <% resources.each do |resource| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-image">
            <%= image_tag resource.images.url() %>
            <span class="card-title"><%= link_to resource.title, resource %></span>
          </div>
          <!--<div class="card-content">
            <h4><%= link_to resource.title, resource %></h4>
          </div>-->
          <div class="card-action">
            <p>Submited <%= time_ago_in_words(resource.created_at - 1) %> in <%= link_to resource.category.category_name , category_path(resource.category.slug) %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    <div class="text-center">
      <%= paginate @resource %>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted"> Pixfuel Copyright 2015.</p>
    </div>
  </footer>