config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'admin/dashboard' => 'admins#dashboard'
  resources 'categories'
  resources 'resources'
  root 'homepage#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Pixfuel - Web & Design Resources</title>
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content="" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="" />
    <meta property="og:description"   content="" />
    <meta property="og:image"         content="" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<!--<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= link_to "Sign In", new_admin_session_path %><br/>
	<% if admin_signed_in? %>
	<%= link_to "Sign Out", destroy_admin_session_path , :method => 'delete' %>
	<% end %>-->
<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Pixfuel - Web & Design Resources</title>
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content="" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="" />
    <meta property="og:description"   content="" />
    <meta property="og:image"         content="" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<!--<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= link_to "Sign In", new_admin_session_path %><br/>
	<% if admin_signed_in? %>
	<%= link_to "Sign Out", destroy_admin_session_path , :method => 'delete' %>
	<% end %>-->
<%= yield %>

</body>
</html>